hostname_prefix: "server"
static_ip: "192.168.122.88{{ inventory_hostname.split('server')[1] }}"
gateway: "192.168.1.1"
new_users:
  - username: "user1"
    pub_key: "ssh-rsa AAAAB3NzaC1yc2E..."
  - username: "user2"
    pub_key: "ssh-rsa AAAAB3NzaC1yc2E..."
